name: VotingSample
services:
- name: vote
  project: vote/vote.csproj
- name: redis
  image: redis
  bindings:
    - port: 6379
      connectionString: ${host}:${port}
- name: worker
  project: worker/worker.csproj
- name: postgres
  image:  postgres
  env:
  - name: POSTGRES_PASSWORD
    value: "pass@word1"
  bindings:
  - port: 5432
    connectionString: Server=${host};Port=${port};User Id=postgres;Password=${env:POSTGRES_PASSWORD};
- name: results
  project: results/results.csproj
  bindings:
  - name: http
    protocol: http
  env:
  - name: public-ip
    # value: http://52.159.20.103
    value: http://localhost:8080
- name: identityserver
  project: IdentityServer/IdentityServer.csproj
  bindings:
  - name: http
    protocol: http
  env:
  - name: public-ip
    # value: http://52.159.20.103
    value: http://localhost:8080
ingress:
  - name: ingress
    bindings:
    - protocol: http
      port: 8080
    rules:
      - path: /vote
        service: vote
        preservePath: true
      - path: /results
        service: results
        preservePath: true
      - path: /identityserver
        service: identityserver
        preservePath: true
