app: multi-tye # name of the bigger application
name: backend # name of this application
services:
- name: backend
  project: backend/backend.csproj
- name: worker
  project: worker/worker.csproj
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672