# tye application configuration file
# read all about it at https://github.com/dotnet/tye
name: multi-project
services:
- name: backend
  project: backend/backend.csproj
- name: frontend
  project: frontend/frontend.csproj
  replicas: 2
- name: worker
  project: worker/worker.csproj
- name: rabbit
  image: rabbitmq:3-management
  bindings:
    - port: 5672
dependencies:
  - path: ../single-project/tye.yaml